### ISSUE TITLE
Unable to link to Hue app

### ISSUE THREAD

**Issue by MTrab** [marcelveldt/hass_emulated_hue#3] opened 2020-02-13 16:33 UTC
When trying to link to Hue app, it just times out (even thou I enabled Link mode from HA)

Any ideas?

**Comment by marcelveldt** [comment] 2020-02-13 16:39
When you enable link mode, you should get a confirmation in the browser that link mode is enabled.
After that you have 30 seconds to connect the Hue app.

Also note that it might be needed to reinstall the Hue app to prevent any traces from caching

**Comment by MTrab** [comment] 2020-02-13 16:40
Yup - I get the confirmation.
And the app is a clean install (haven't had it installed for a month or so)

**Comment by MTrab** [comment] 2020-02-13 16:47
Now I, somehow, succeded in linking - but now the Hue app just crashes whenever I open it.

**Comment by MTrab** [comment] 2020-02-13 16:48
ARNING emulated_hue.hue_api.hue_api -- Invalid request: <Request PUT /api/f196c809380e4aad80eb/config > --> {'UTC': '2020-02-13T16:47:23'}

**Comment by marcelveldt** [comment] 2020-02-13 16:50
Ah, thanks. Looks like the app is trying to write the date to the config :-)
I've been testing on the iOS app. Am I correct if to conclude you're using the Android app ?
I'll put a quick fix in the code.

**Comment by MTrab** [comment] 2020-02-13 16:50
Exactly - I'm on Android.

**Comment by marcelveldt** [comment] 2020-02-13 17:00
new version is up on the repo: addon version 0.02
can you give that version a try ?

**Comment by MTrab** [comment] 2020-02-13 17:07
For some reason my HassIO won't pickup the latest version. Still version 0.0.1 installed.

**Comment by marcelveldt** [comment] 2020-02-13 17:07
press the little refresh icon in the rop right....

**Comment by marcelveldt** [comment] 2020-02-13 17:09
![Schermafbeelding 2020-02-13 om 18 07 57](https://user-images.githubusercontent.com/6389780/74459650-fa996900-4e8b-11ea-9304-c3d2edf6a4dc.png)

**Comment by MTrab** [comment] 2020-02-13 17:10
Eeewww - now it went really bad:

```
2020-02-13 17:09:40,386 INFO  emulated_hue.config.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2020-02-13 17:09:40,460 INFO  emulated_hue.hue_api.hue_api -- Client Hue 3#OnePlus ONEPLUS A50 registered
2020-02-13 17:09:40,606 ERROR aiohttp.server.web_protocol -- Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/app/emulated_hue/hue_api.py", line 71, in func_wrapper
    return await func(cls, request)
  File "/usr/local/app/emulated_hue/hue_api.py", line 393, in get_full_state
    return web.json_response(json_response)
  File "/usr/lib/python3.7/site-packages/aiohttp/web_response.py", line 715, in json_response
    text = dumps(data)
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
```

**Comment by marcelveldt** [comment] 2020-02-13 17:18
Well, it's now one step further :-) 
Let me do some debugging, moment....

**Comment by marcelveldt** [comment] 2020-02-13 17:24
OK, I introduces a sloppy bug. Now fixed in 0.0.3

**Comment by MTrab** [comment] 2020-02-13 17:36
Nah - still looks pretty much the same:

```
2020-02-13 17:35:18,564 ERROR aiohttp.server.web_protocol -- Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/app/emulated_hue/hue_api.py", line 71, in func_wrapper
    return await func(cls, request)
  File "/usr/local/app/emulated_hue/hue_api.py", line 393, in get_full_state
    return web.json_response(json_response)
  File "/usr/lib/python3.7/site-packages/aiohttp/web_response.py", line 715, in json_response
    text = dumps(data)
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
```

**Comment by marcelveldt** [comment] 2020-02-13 17:38
did you update to 0.0.3 ?

**Comment by MTrab** [comment] 2020-02-13 17:48
Yes I did

**Comment by marcelveldt** [comment] 2020-02-13 17:58
Please click rebuild...

**Comment by MTrab** [comment] 2020-02-13 17:59
Still the same

**Comment by marcelveldt** [comment] 2020-02-13 18:00
It's still using the old python code as the docker image isn't rebuilt.
Reinstall to test yourself or wait for me to prebuild the images

**Comment by MTrab** [comment] 2020-02-13 18:16
Tried reinstalling and the error dissapeared - but still the app was not working.
Removed app and app data, but now I can't pair again.
Just ends up with a request link on HA, when pressing that (and getting confirmation) the app just returns no new Hue bridges detected.

**Comment by marcelveldt** [comment] 2020-02-13 18:17
Ok and in the add-on logs ?

**Comment by MTrab** [comment] 2020-02-13 18:17
```
2020-02-13 18:11:13,530 INFO Set uid to user 0 succeeded
2020-02-13 18:11:13,532 INFO supervisord started with pid 7
2020-02-13 18:11:14,535 INFO spawned: 'hue' with pid 9
2020-02-13 18:11:14,863 INFO  emulated_hue.config.config -- Listen IP address not specified, auto-detected address is 10.254.254.109
2020-02-13 18:11:15,398 INFO  emulated_hue.hue_api.hue_api -- Started HTTP webserver on port 80
2020-02-13 18:11:15,463 INFO  emulated_hue.hue_api.hue_api -- Started HTTPS webserver on port 443
2020-02-13 18:11:16,466 INFO success: hue entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-02-13 18:12:28,866 INFO  emulated_hue.config.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2020-02-13 18:12:34,862 INFO  emulated_hue.config.config -- Link mode is enabled for the next 30 seconds.
2020-02-13 18:12:47,190 INFO  emulated_hue.config.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2020-02-13 18:12:54,831 INFO  emulated_hue.config.config -- Link mode is enabled for the next 30 seconds.
2020-02-13 18:13:04,864 INFO  emulated_hue.config.config -- Link mode is disabled.
2020-02-13 18:13:24,833 INFO  emulated_hue.config.config -- Link mode is disabled.
2020-02-13 18:13:56,554 INFO  emulated_hue.config.config -- Link mode is enabled for the next 30 seconds.
2020-02-13 18:14:21,354 INFO  emulated_hue.config.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2020-02-13 18:14:26,555 INFO  emulated_hue.config.config -- Link mode is disabled.
2020-02-13 18:14:27,779 INFO  emulated_hue.config.config -- Link mode is enabled for the next 30 seconds.
2020-02-13 18:14:33,909 INFO  emulated_hue.config.config -- Link mode is enabled for the next 30 seconds.
2020-02-13 18:14:51,443 INFO  emulated_hue.config.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2020-02-13 18:14:55,136 INFO  emulated_hue.config.config -- Link mode is enabled for the next 30 seconds.
2020-02-13 18:14:57,781 INFO  emulated_hue.config.config -- Link mode is disabled.
2020-02-13 18:15:03,422 INFO  emulated_hue.config.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2020-02-13 18:15:03,910 INFO  emulated_hue.config.config -- Link mode is disabled.
2020-02-13 18:15:09,330 INFO  emulated_hue.config.config -- Link mode is enabled for the next 30 seconds.
2020-02-13 18:15:25,138 INFO  emulated_hue.config.config -- Link mode is disabled.
2020-02-13 18:15:39,331 INFO  emulated_hue.config.config -- Link mode is disabled.
```

**Comment by marcelveldt** [comment] 2020-02-13 18:27
Sorry for the fuss. Did you reinstall the HUE app AFTER reinstalling the add-on ?
The Hue app keeps a cache for the unique bridge connection. Reinstalling the addon create a new unique id for the bridge on the same mac.

**Comment by MTrab** [comment] 2020-02-13 18:27
Yes - cleaned app data and reinstalled Hue app AFTER the add-on.

**Comment by allanpersson** [comment] 2020-02-13 18:39
I experience the same as @MTrab on 0.0.3, with uninstalls and cleared cache 🙏

**Comment by MADS0LADEN** [comment] 2020-02-13 20:21
Same here.
It registers the device, but crashes the app every time i open it
```
Addon logs:
2020-02-13 20:17:47,137 INFO  emulated_hue.config.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2020-02-13 20:17:52,730 INFO  emulated_hue.config.config -- Link mode is enabled for the next 30 seconds.
2020-02-13 20:18:12,638 INFO  emulated_hue.config.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2020-02-13 20:18:13,094 INFO  emulated_hue.config.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2020-02-13 20:18:13,192 INFO  emulated_hue.hue_api.hue_api -- Client Hue 3#OnePlus ONEPLUS A60 registered

Supervisor logs:
20-02-13 20:16:01 INFO (SyncWorker_0) [hassio.docker.interface] Clean addon_62c7908d_emulated_hue application
20-02-13 20:16:01 INFO (SyncWorker_0) [hassio.docker.interface] Remove image 62c7908d/amd64-addon-emulated_hue with latest and 0.0.3
20-02-13 20:16:01 INFO (SyncWorker_14) [hassio.docker.addon] Start build 62c7908d/amd64-addon-emulated_hue:0.0.3
20-02-13 20:16:04 INFO (SyncWorker_14) [hassio.docker.addon] Build 62c7908d/amd64-addon-emulated_hue:0.0.3 done
20-02-13 20:16:04 INFO (MainThread) [hassio.addons] Add-on '62c7908d_emulated_hue' successfully rebuilt
20-02-13 20:16:04 INFO (SyncWorker_16) [hassio.docker.addon] Start Docker add-on 62c7908d/amd64-addon-emulated_hue with version 0.0.3

**Comment by marcelveldt** [comment] 2020-02-13 20:23
OK thanks. I will try to get my hands on an Android device to test it out.
Been testing with iOS devices so far.

**Comment by marcelveldt** [comment] 2020-02-13 20:26
Any one of you tried the Hue Sync app on pc/mac ?

**Comment by MTrab** [comment] 2020-02-13 21:12
> Any one of you tried the Hue Sync app on pc/mac ?

Apparently I'm not able to manually specify the IP address for Home Assistant in Hue Sync - so I cannot confirm if it's working or not.

My PC and Home Assistant are on 2 different VLANs, so discovery are not working.

**Comment by marcelveldt** [comment] 2020-02-13 21:30
Issue confirmed. On Android the app crashes. Probably it's missing some info it expects and the error is not very well handled in the app. The iOS app does not have this issue so I did not discover it. Will hunt for the cause and fix it. To be continued...

**Comment by marcelveldt** [comment] 2020-02-13 22:55
OK, fixed. New version 0.0.4 of the addon is now on the repo.

**Comment by marcelveldt** [comment] 2020-02-13 22:57
BTW: I discovered I still need to handle some of the functions in the app like default scenes and toggle between color and white. Will do so tomorrow.

**Comment by allanpersson** [comment] 2020-02-14 08:28
I can confirm it's working with 0.0.4 🙏
🙌 Thanks for the addon and for putting resources in fixing this issue so fast 👏

**Comment by MTrab** [comment] 2020-02-14 13:36
Needed to clear out all Hue data again, but now it looks like it's working.

Next problem is my TV which is on another VLAN, I don't seem to be able to enter an IP address manually - but that's not related to this add-on in any way. ;)

**Comment by marcelveldt** [comment] 2020-02-14 16:01
OK great.
My experience is that home equipment does not play well with multiple vlans and other "corporate" stuff. Multicast traffic, discovery etc.

My router/firewall (ubiquiti) has an option to route discovery traffic across multiple VLAN's/networks.

**Comment by MTrab** [comment] 2020-02-14 16:17
I have Unifi too, I have enabled IGMP snooping on the IoT net, but discovery aren't working thou.

**Comment by marcelveldt** [comment] 2020-02-14 16:33
IGMP snooping will only make sure multicast traffic is only sent to the correct destinations, it won't fix your discovery packages travelling across different networks. Let me quickly check what the name of the feature is...

**Comment by marcelveldt** [comment] 2020-02-14 16:35
![Schermafbeelding 2020-02-14 om 17 35 26](https://user-images.githubusercontent.com/6389780/74549716-647b4680-4f50-11ea-8fec-b4b852d301b1.png)

**Comment by MTrab** [comment] 2020-02-14 17:03
I have that enabled too - but perhaps one of my firewall rules are preventing it to crossover from IoT to normal (my IoT net is REALLY restricted :D)

**Closed** 2020-02-28 22:55 UTC

**Comment by carsaig** [comment] 2020-12-23 17:30
Hi Marcel,
I highly appreciate your effort! The emulation is exactly what I am looking for. Though - not successful yet.
I am still having issues, I'm afraid.. I can get the mac app (hue sync) or hue app on iOS discover the bridge alright, but then things go sideways. The notification for the linking request shows up alright. After clicking it, the linking confirmation message is not showing anywhere in the HASSIO UI. No idea where I should confirm the bridge link. 
The timer in the mac app counts down and returns to bridge search again because I was unable to confirm the linkage.
The iOS app sort of connects as it seems but as soon as I try to add lights, I get the following error:

`Dec 23 18:06:25 pi 014dee03d275[460]: 2020-12-23 17:06:25,510 ERROR aiohttp.server -- Error handling request
Dec 23 18:06:25 pi 014dee03d275[460]: Traceback (most recent call last):
Dec 23 18:06:25 pi 014dee03d275[460]:   File "/usr/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
Dec 23 18:06:25 pi 014dee03d275[460]:     resp = await self._request_handler(request)
Dec 23 18:06:25 pi 014dee03d275[460]:   File "/usr/lib/python3.7/site-packages/aiohttp/web_app.py", line 499, in _handle
Dec 23 18:06:25 pi 014dee03d275[460]:     resp = await handler(request)
Dec 23 18:06:25 pi 014dee03d275[460]:   File "/usr/local/app/emulated_hue/hue_api.py", line 506, in unknown_request
Dec 23 18:06:25 pi 014dee03d275[460]:     request_data = await request.json()
Dec 23 18:06:25 pi 014dee03d275[460]:   File "/usr/lib/python3.7/site-packages/aiohttp/web_request.py", line 614, in json
Dec 23 18:06:25 pi 014dee03d275[460]:     return loads(body)
Dec 23 18:06:25 pi 014dee03d275[460]:   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
Dec 23 18:06:25 pi 014dee03d275[460]:     return _default_decoder.decode(s)
Dec 23 18:06:25 pi 014dee03d275[460]:   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
Dec 23 18:06:25 pi 014dee03d275[460]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Dec 23 18:06:25 pi 014dee03d275[460]:   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
Dec 23 18:06:25 pi 014dee03d275[460]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Dec 23 18:06:25 pi 014dee03d275[460]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
Any suggestions?

**Comment by simplemice** [comment] 2023-06-12 03:13
![Screenshot from 2023-06-12 10-13-05](https://github.com/hass-emulated-hue/core/assets/41122465/4fe13278-3d03-41b3-a532-c295aeb5fa1d)
![Screenshot from 2023-06-12 10-12-46](https://github.com/hass-emulated-hue/core/assets/41122465/89e41285-c718-49a5-a04f-5075194cec2f)

2023-06-12 10:11:30,281 ERROR emulated_hue.apiv1 -- Pairing with Home Assistant is explicitly disabled.
2023-06-12 10:11:30,285 ERROR emulated_hue.apiv1 -- Pairing with Home Assistant is explicitly disabled.

how to enable?
