### ISSUE TITLE
Unable to install from within hassio

### ISSUE THREAD

**Issue by hostrup** [marcelveldt/hass_emulated_hue#1] opened 2020-02-13 08:52 UTC
Hi! 
I am trying to install this addon - using the supervisor ( running  hassio version: 0.105.3 on Ubuntu 18.04.4 LTS ) 

But i get an error - saying: Failed to install addon, [object Object]

![hue_bridge](https://user-images.githubusercontent.com/59999266/74417118-7d97d080-4e46-11ea-8dd5-48331d6d5e9a.png)

I am not sure if its because i am running on ubuntu - or because  have allready used port 80 and 443 by other docker containers? 

br Ronni

**Comment by marcelveldt** [comment] 2020-02-13 08:58
Hi Ronni, what platform are you on ? I actually only tested this on amd64/Intel NUC.

As soon as you get the install failed message, navigate to the system tab of the supervisor.
The log will show some info about the docker command that failed.

**Comment by hostrup** [comment] 2020-02-13 09:01
Hi Marcel: 

i get these error in the logs: 

20-02-13 08:59:25 INFO (SyncWorker_0) [hassio.docker.addon] Start build 62c7908d/amd64-addon-emulated_hue:0.0.1
20-02-13 08:59:25 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 153, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 61, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/addons/__init__.py", line 132, in install
    await addon.instance.install(store.version, store.image)
  File "/usr/src/hassio/hassio/utils/__init__.py", line 29, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/hassio/hassio/docker/addon.py", line 374, in _install
    self._build(tag)
  File "/usr/src/hassio/hassio/docker/addon.py", line 388, in _build
    use_config_proxy=False, **build_env.get_docker_args(tag)
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 279, in build
    resp = self.client.api.build(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/build.py", line 160, in build
    path, exclude=exclude, dockerfile=dockerfile, gzip=gzip
  File "/usr/local/lib/python3.7/site-packages/docker/utils/build.py", line 31, in tar
    root=root, fileobj=fileobj, gzip=gzip, extra_files=extra_files
  File "/usr/local/lib/python3.7/site-packages/docker/utils/build.py", line 68, in create_archive
    fileobj = tempfile.NamedTemporaryFile()
  File "/usr/local/lib/python3.7/tempfile.py", line 538, in NamedTemporaryFile
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
  File "/usr/local/lib/python3.7/tempfile.py", line 126, in _sanitize_params
    dir = gettempdir()
  File "/usr/local/lib/python3.7/tempfile.py", line 294, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/local/lib/python3.7/tempfile.py", line 229, in _get_default_tempdir
    dirlist)
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']


looks like the aiohttp is not able to build - maybe i am missing some components on my host-os

**Comment by marcelveldt** [comment] 2020-02-13 09:05
Looks like it doesn't even come that far. It's hassio/supervisor itself failing to build the image.
So yes, the problem is in your host OS. To be exactly: make sure that there is a writable temp location...

**Comment by marcelveldt** [comment] 2020-02-13 09:05
Maybe I can put up some prebuilt images later today, so it doesntt need to be locally built

**Comment by marcelveldt** [comment] 2020-02-13 09:10
btw: what theme are you using in hass ? Looks good!

**Comment by hostrup** [comment] 2020-02-13 09:13
Hi Marcel! 
I should think that i should be possible to build images - and that it should be possible to write to the locations - but i can have a look. 

A prebuilt image could be a solution - but  dont put to much work into it for me - because i have just realized that i dont have any free ports on my server  - so for this to work - i think i must run it on another server / virtual server. or maybe some bridge mode - since i have a nginx reverse proxy allready taking up port 80 / 443 :) 

But thanks alot for your support!

**Comment by marcelveldt** [comment] 2020-02-13 09:15
as you're running the host OS yourself, you can try to set up a new network bridge and run the docker container on that

**Comment by MTrab** [comment] 2020-02-13 09:28
I see similar error when installing on my HassIO.
I run a Debian host for my HassIO setup and nothing occupying the ports (80 and 443)

Have no problems with your Auto Backup addin.

**Comment by hostrup** [comment] 2020-02-13 09:30
> as you're running the host OS yourself, you can try to set up a new network bridge and run the docker container on that

I could give that a try :)

**Comment by MTrab** [comment] 2020-02-13 09:31
I tried a second time, and now it installed. Strange.

**Comment by marcelveldt** [comment] 2020-02-13 09:41
> I tried a second time, and now it installed. Strange.

The images are not yet prebuilt so it will use your host to build the image which can take some time. At a later stage I will facilitate prebuilt images on the repo.

**Comment by konradwalsh** [comment] 2020-03-09 11:20
Is this still an issue?

I tried to install on HASSIO and I get this


`20-03-09 11:12:15 INFO (SyncWorker_2) [hassio.docker.addon] Start build 62c7908d/amd64-addon-emulated_hue:0.0.4
20-03-09 11:12:31 ERROR (SyncWorker_2) [hassio.docker.addon] Can't build 62c7908d/amd64-addon-emulated_hue:0.0.4: The command '/bin/sh -c apk add --no-cache --virtual .build-dependencies         build-base         cmake         libuv-dev         libffi-dev         python3-dev         openssl-dev         git     && apk add --no-cache         python3         openssl         supervisor     && mkdir /usr/local/app     && git clone https://github.com/marcelveldt/hass_emulated_hue.git     && pip3 install         --no-cache-dir         -r hass_emulated_hue/requirements.txt     && cp -R hass_emulated_hue/emulated_hue /usr/local/app/     && cp hass_emulated_hue/run.py /usr/local/app/run.py     && apk del --no-cache --purge .build-dependencies     && find /usr/local         \( -type d -a -name test -o -name tests -o -name '__pycache__' \)         -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \)         -exec rm -rf '{}' +     && rm -f -r         /root/.cache         /root/.cmake         /tmp/*         hass_emulated_hue' returned a non-zero code: 8`

**Comment by konradwalsh** [comment] 2020-03-09 21:15
ok.. weird.. i just tried to install now and it worked!

However, I now have the port cannot be set.. off to figure this out

**Comment by marcelveldt** [comment] 2020-12-30 20:52
Prebuilt images are now available so installing the addon should go fast now. Closing this issue as it's a bit outdated.

**Closed by marcelveldt** 2020-12-30 20:52 UTC
Labels: no-issue-activity
